name: Main

on:
  push:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.head.repo.full_name || github.repository }}-${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

jobs:
  cmake_and_ctest:
    name: "CMake & CTest, ${{ matrix.cmake-type }} ${{ matrix.variant.os }}, py${{ matrix.python-version }}"
    runs-on: ${{ matrix.variant.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - { os: ubuntu-latest} 
          - { os: macos-26-intel}     
          - { os: macos-26}    
          - { os: windows-latest} 
        python-version: ["3.12"]
        cmake-type: ["Debug", "Release"]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python-based dependencies
        run: |
          python -m pip install conan numpy
          echo "pythonInterpreter=`which python`" >> $GITHUB_ENV

      - name: Cache conan setup
        id: conan-cache-key
        run: |
          echo "key=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
          echo "path=$(conan config home)" >> $GITHUB_OUTPUT

      - name: Cache conan
        uses: actions/cache@v7
        with:
          path: ${{ steps.conan-cache-key.outputs.path }}
          key: conan-${{ matrix.variant.os }}-${{ steps.conan-cache-key.outputs.key }}

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.cmake-type }} -D Python3_EXECUTABLE=${{ env.pythonInterpreter }}

      - name: build
        run: cmake --build build --config ${{ matrix.cmake-type }} -j

      - name: test
        working-directory: build
        run: ctest -C ${{ matrix.cmake-type }} --verbose -j

  integration_tests:
    name: "Python integration tests, ${{ matrix.variant.os }} ${{ matrix.mpi }}"
    runs-on: ${{ matrix.variant.os }}
    needs: cmake_and_ctest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - { os: ubuntu-latest }
        mpi: [ 'mpich', 'openmpi', 'intelmpi']
        python-version: ["3.12"]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libhdf5-dev

      - name: Install Python-based dependencies
        run: |
          python -m pip install conan numpy mccode-antlr pytest h5py

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build with development mode
        run: |
          cmake -S . -B build-dev
          cmake --build build-dev -j

      - name: Run integration tests
        run: python -m pytest tests/ -v --tb=short
